#!/bin/bash

# Cursor AI Shell Script Helper
# Provides proper shell script templates for Cursor AI

echo "Cursor AI Shell Script Helper"
echo "============================="
echo ""

# Function to generate proper shell script template
generate_shell_template() {
    local script_name="$1"
    
    cat > "$script_name" << 'TEMPLATE_EOF'
#!/bin/bash

# Generated by Cursor AI with proper formatting
echo "Script starting"
echo "==============="
echo ""
echo "Status: Running"
echo "Progress: 0%"
echo ""
echo "Processing..."
echo "Status: Complete"
echo ""
echo "Script finished"
TEMPLATE_EOF
    
    chmod +x "$script_name"
    echo "✅ Generated proper shell script: $script_name"
}

# Function to validate shell script
validate_shell_script() {
    local script="$1"
    
    echo "Validating: $script"
    
    # Check for problematic patterns
    if grep -q 'echo.*".*$' "$script" && grep -A1 'echo.*".*$' "$script" | grep -q 'echo'; then
        echo "❌ Multi-line echo detected"
        return 1
    fi
    
    if grep -q 'echo.*"[^"]*$' "$script"; then
        echo "❌ Unclosed quote detected"
        return 1
    fi
    
    echo "✅ Script validation passed"
    return 0
}

# Main execution
main() {
    echo "Cursor AI Shell Script Helper loaded"
    echo "Available functions:"
    echo "  generate_shell_template <filename>"
    echo "  validate_shell_script <filename>"
}

main "$@"
