#!/bin/bash

# Alex AI Universal Credentials Loader
# This script loads credentials from ~/.zshrc and makes them available
# throughout the entire monorepo workflow for CI/CD and deployment

set -e

echo "🔐 Alex AI Universal Credentials Loader"
echo "======================================"

# Source the user's zshrc file to get all credentials
if [ -f ~/.zshrc ]; then
    echo "📁 Loading credentials from ~/.zshrc..."
    # Extract only export statements to avoid zsh-specific commands
    grep "^export " ~/.zshrc | while read line; do
        eval "$line"
    done
    echo "✅ Credentials loaded successfully"
else
    echo "⚠️  ~/.zshrc not found, using environment variables"
fi

# Export all Alex AI related environment variables
export_vars=(
    "NEXT_PUBLIC_SUPABASE_URL"
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
    "N8N_URL"
    "N8N_API_KEY"
    "OPENAI_API_KEY"
    "ANTHROPIC_API_KEY"
    "OPENROUTER_API_KEY"
    "GITHUB_TOKEN"
    "ALEX_AI_ENVIRONMENT"
    "ALEX_AI_VERSION"
)

# Map Supabase credentials from your ~/.zshrc format to Next.js format
if [ -n "$SUPABASE_URL" ]; then
    export NEXT_PUBLIC_SUPABASE_URL="$SUPABASE_URL"
fi

if [ -n "$SUPABASE_ANON_KEY" ]; then
    export NEXT_PUBLIC_SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"
fi

if [ -n "$SUPABASE_KEY" ]; then
    export NEXT_PUBLIC_SUPABASE_ANON_KEY="$SUPABASE_KEY"
fi

echo "🌐 Exporting environment variables:"
for var in "${export_vars[@]}"; do
    if [ -n "${!var}" ]; then
        echo "  ✅ $var"
        export "$var"
    else
        echo "  ⚠️  $var (not set)"
    fi
done

# Create .env files for each app in the monorepo
echo "📝 Creating .env files for monorepo apps..."

# Alex AI Job Search App
cat > apps/alex-ai-job-search/.env.local << EOF
# Alex AI Job Search Environment Variables
# Generated by Alex AI Universal Credentials Loader
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
N8N_URL=${N8N_URL:-https://n8n.pbradygeorgen.com}
N8N_API_KEY=${N8N_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
ALEX_AI_ENVIRONMENT=${ALEX_AI_ENVIRONMENT:-development}
ALEX_AI_VERSION=${ALEX_AI_VERSION:-1.0.0}
EOF

# Add other apps as needed
# cat > apps/other-app/.env.local << EOF
# ... environment variables
# EOF

echo "✅ .env.local files created for all apps"

# Create a global .env file for the monorepo
cat > .env << EOF
# Alex AI Monorepo Global Environment Variables
# Generated by Alex AI Universal Credentials Loader
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
N8N_URL=${N8N_URL:-https://n8n.pbradygeorgen.com}
N8N_API_KEY=${N8N_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
GITHUB_TOKEN=${GITHUB_TOKEN}
ALEX_AI_ENVIRONMENT=${ALEX_AI_ENVIRONMENT:-development}
ALEX_AI_VERSION=${ALEX_AI_VERSION:-1.0.0}
EOF

echo "✅ Global .env file created"

# Verify credentials are accessible
echo "🔍 Verifying credential accessibility..."
if [ -n "$NEXT_PUBLIC_SUPABASE_URL" ] && [ -n "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ]; then
    echo "  ✅ Supabase credentials available"
else
    echo "  ❌ Supabase credentials missing"
fi

if [ -n "$N8N_URL" ] && [ -n "$N8N_API_KEY" ]; then
    echo "  ✅ N8N Federation Crew credentials available"
else
    echo "  ❌ N8N Federation Crew credentials missing"
fi

if [ -n "$OPENAI_API_KEY" ] || [ -n "$ANTHROPIC_API_KEY" ] || [ -n "$OPENROUTER_API_KEY" ]; then
    echo "  ✅ LLM API credentials available"
else
    echo "  ❌ LLM API credentials missing"
fi

echo ""
echo "🎉 Alex AI Universal Credentials Loader Complete!"
echo "All credentials are now available throughout the monorepo."
echo ""
echo "Next steps:"
echo "1. Run 'npm run dev' in any app directory"
echo "2. Credentials will be automatically loaded"
echo "3. CI/CD pipelines will use these credentials"
echo ""
